site_name: 星陵祭オンライン整理券
theme:
  language: ja
  name: material
  palette:
    scheme: default
    primary: light blue
    accent: indigo
  font:
    text: Noto Sans JP
    code: Roboto Mono
  logo: assets/logo.png

nav:
  - "seiryofes.comへ": https://seiryofes.com
  - "星陵祭オンライン整理券システムの使い方": index.md
  - "オンライン整理券システムの制作背景・実現する機能": features.md
  - "クラ代・団体代表者":
      - "団体情報の編集": owner/manage_group.md
  - "チーフ会入校処理担当者":
      - "来校者の入校処理とは": entry/about.md
  - "開発者・管理者向け":
      - "はじめに": developers/index.md
          - "はじめに2": developers/index.md
      - "アプリケーションの構成": developer/app_structure.md
      - "権限について": developer/role.md
      - "フロントエンドのビルド": developer/build_frontend.md
      - "APIサーバーの構成": developer/api_server.md
      - "APIドキュメント (Swagger UI)の使い方": developer/api_docs.md

  - "IT委員会勉強会資料":
      - "もくじ": studybook/index.md
      - "春休み0日目 環境構築": studybook/spring_day0_setup_environment.md
      - "春休み1日目 ツールの使い方": studybook/spring_day1_tutorial.md
      - "春休み2日目 Nuxt.js入門": studybook/spring_day2_nuxtjs.md
