site_name: 星陵祭オンライン整理券
theme:
  language: ja
  name: material
  palette:
    scheme: default
    primary: light blue
    accent: indigo
  font:
      text: Noto Sans JP
      code: Roboto Mono
  logo: assets/logo.png